name: Semantic-Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 15.13.28  # It is recommended to specify specifying version range
                                    # for semantic-release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

